### ISSUE TITLE
'React' not found

### ISSUE THREAD

**Issue by teohweijing** [Faradey27/react-formula-beautifier#4]
When I insert `<TeX value={this.state.formula} />` I  got "React not found error". 
The reason I found is as below.
At TeX.js, react is initiated at line 9 as `var _react = require('react');`
However, at line 51 you call createElement method with `React.createElement`

**Comment by Faradey27** [comment]
strange issue, will try to reproduce and fix soon

**Comment by Faradey27** [comment]
@teohweijing sorry for delay, i think currently you are using not last version of lib, pls update and confirm that problem disappear 

also general solution:

just add webpack plugin 

new webpack.ProvidePlugin({
      'React': 'react',
    }),

to your webpack config

**Comment by teohweijing** [comment]
@Faradey27 Hey, you are right. I just read your latest version of codes and that part was fixed by changing `React.createElement` to `_react.createElement`. My bad, thanks for reminding though.
