### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by poiuqwer78** [Faradey27/react-formula-beautifier#6]
Hi

Your component lists two dependencies (react, mathjax). I belive you should remove both dependencies, as MathJax is available via the script import (and so doesn't require any local files) and react is already listed as peer dependency, which is the better choice.

I removed those dependencies and your component still works perfectly, as long as there is react in the project (as peer).

**Comment by Faradey27** [comment]
@poiuqwer78 sorry for delay,
should be solved now
